// import proposalimg from '../../assets/dashboard/proposalimg.svg'

export const jobListings = []


<<<<<<< HEAD
// export const jobListings = [
//     { id: 1,  
//       image: proposalimg, 
//       timePosted: "11 mins",    
//       title: "Junior Developer", 
//       name:"Mraz, Quigley and Feest Inc.", 
//       hoursPerWeek: "30",
//       salary: "$20",
//       location: "Abia",
//       degree: "Bsc",
//       experienceYears: "2 Years",
//       hoursPerWeek: "30",
//       category: "Construction",
//       experience: "No-experience", 
//       datePosted: "Last 7 Days" ,
//        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
//     },
//     { id: 2,  
//       image: proposalimg, 
//       timePosted: "11 mins",   
//       title: "React Engineer", 
//       name:"Mraz, Quigley and Feest Inc.", 
//       hoursPerWeek: "80",
//       salary: "$90",
//       location: "osun",
//       degree: "Masters",
//       experienceYears: "2 Years",
//       hoursPerWeek: "20",
//       category: "Construction",
//       experience: "Intermediate", 
//       datePosted: "Last 24 Hours" ,
//       description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
//     },
//     { id: 3,
//       image: proposalimg, timePosted: "11 mins",  
//       title: "Senior Developer", 
//       name:"Mraz, Quigley and Feest Inc.", 
//       experience: "Expert", 
//       experienceYears: "2 Years",
//       datePosted: "Last Hour" ,
//       hoursPerWeek: "50",
//       degree: "Bsc",
//       salary: "$40",
//       location: "Edo",
//       hoursPerWeek: "70",
//       category: "Construction",
//       description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
//      },
      
//     { id: 4, 
//       image: proposalimg, 
//       timePosted: "11 mins",    
//       title: "Frontend Developer", 
//       name:"Mraz, Quigley and Feest Inc.", 
//       experience: "Fresher", 
//       experienceYears: "2 Years",
//       datePosted: "Last 30 Days",
//       hoursPerWeek: "60",
//       degree: "Bsc",
//       salary: "$60",
//       location: "Abuja",
//       hoursPerWeek: "30",
//       category: "Construction",
//       description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
//      },
//     { id: 5, 
//       image: proposalimg, 
//       timePosted: "11 mins",    
//       title: "Backend Developer", 
//       name:"Mraz, Quigley and Feest Inc.", 
//       experience: "Intermediate", 
//       experienceYears: "2 Years",
//       datePosted: "All" ,
//       hoursPerWeek: "80",
//       salary: "$100",
//       degree: "Masters",
//       location: "Abuja",
//       hoursPerWeek: "30",
//       category: "Technology",
//       description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
//     },
//     { id: 6, 
//       image: proposalimg, 
//       timePosted: "11 mins",   
//       title: "Product Designer", 
//       name:"Mraz, Quigley and Feest Inc.", 
//       experience: "Fresher", 
//       experienceYears: "2 Years",
//       datePosted: "Last 7 Days",
//       hoursPerWeek: "60",
//       degree: "Bsc",
//       salary: "$60",
//       location: "Abuja",
//       hoursPerWeek: "30",
//       category: "Arts & Crafts",
//       description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
//      },
//     { id: 7, 
//       image: proposalimg, 
//       timePosted: "11 mins",   
//       title: "DevOps Engineer", 
//       name:"Mraz, Quigley and Feest Inc.", 
//       experience: "Expert", 
//       experienceYears: "2 Years",
//       degree: "Bsc",
//       datePosted: "Last 24 Hours" ,
//       hoursPerWeek: "60",
//       salary: "$60",
//       location: "Abuja",
//       hoursPerWeek: "30",
//       category: "Science",
//       description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
//     },
//   ];
=======
export const jobListings = [
    { id: 1,  
      image: proposalimg, 
      timePosted: "11 mins",    
      title: "Junior Developer", 
      name:"Mraz, Quigley and Feest Inc.", 
      hoursPerWeek: "30",
      salary: "$20",
      location: "Abia",
      degree: "Bsc",
      experienceYears: "2 Years",
      category: "Construction",
      experience: "No-experience", 
      datePosted: "Last 7 Days" ,
       description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
    },
    { id: 2,  
      image: proposalimg, 
      timePosted: "11 mins",   
      title: "React Engineer", 
      name:"Mraz, Quigley and Feest Inc.", 
      hoursPerWeek: "80",
      salary: "$90",
      location: "osun",
      degree: "Masters",
      experienceYears: "2 Years",
      category: "Construction",
      experience: "Intermediate", 
      datePosted: "Last 24 Hours" ,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
    },
    { id: 3,
      image: proposalimg, timePosted: "11 mins",  
      title: "Senior Developer", 
      name:"Mraz, Quigley and Feest Inc.", 
      experience: "Expert", 
      experienceYears: "2 Years",
      datePosted: "Last Hour" ,

      degree: "Bsc",
      salary: "$40",
      location: "Edo",
      hoursPerWeek: "70",
      category: "Construction",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
     },
      
    { id: 4, 
      image: proposalimg, 
      timePosted: "11 mins",    
      title: "Frontend Developer", 
      name:"Mraz, Quigley and Feest Inc.", 
      experience: "Fresher", 
      experienceYears: "2 Years",
      datePosted: "Last 30 Days",
      hoursPerWeek: "60",
      degree: "Bsc",
      salary: "$60",
      location: "Abuja",
      category: "Construction",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
     },
    { id: 5, 
      image: proposalimg, 
      timePosted: "11 mins",    
      title: "Backend Developer", 
      name:"Mraz, Quigley and Feest Inc.", 
      experience: "Intermediate", 
      experienceYears: "2 Years",
      datePosted: "All" ,
      hoursPerWeek: "80",
      salary: "$100",
      degree: "Masters",
      location: "Abuja",
      category: "Technology",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
    },
    { id: 6, 
      image: proposalimg, 
      timePosted: "11 mins",   
      title: "Product Designer", 
      name:"Mraz, Quigley and Feest Inc.", 
      experience: "Fresher", 
      experienceYears: "2 Years",
      datePosted: "Last 7 Days",
      hoursPerWeek: "60",
      degree: "Bsc",
      salary: "$60",
      location: "Abuja",
      category: "Arts & Crafts",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
     },
    { id: 7, 
      image: proposalimg, 
      timePosted: "11 mins",   
      title: "DevOps Engineer", 
      name:"Mraz, Quigley and Feest Inc.", 
      experience: "Expert", 
      experienceYears: "2 Years",
      degree: "Bsc",
      datePosted: "Last 24 Hours" ,
      salary: "$60",
      location: "Abuja",
      hoursPerWeek: "30",
      category: "Science",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus. Donec nec nunc id libero ultricies malesuada. Nullam nec nunc id, consectetur adipiscing elit. Sed in urna sit amet dolor egestas luctus.",
    },
  ];
>>>>>>> 222a875... fix error in joblistings file
  